import { defineTheme, flat } from '../../define';

export default defineTheme({
  id: 'classifieds',
  scene: 'usa',
  nativeScheme: 'light',
  name: { es: 'Clasificados', en: 'Classifieds' },
  tagline: { es: 'La pureza de la información: la estética del hipertexto y el minimalismo radical.', en: 'The purity of information: the aesthetics of hypertext and radical minimalism.' },
  reference: {
    title: { es: 'craigslist (sitio web de anuncios clasificados)', en: 'craigslist (classified-ads website)' },
    authors: ['Craig Newmark'],
    date: 1995,
    place: { es: 'San Francisco, Estados Unidos', en: 'San Francisco, United States' },
    kind: 'web',
    sources: [
      { title: 'about > mission and history', url: 'https://www.craigslist.org/about/mission_and_history', publisher: 'craigslist', accessed: '2026-10-05' },
      { title: 'Why Craigslist Is Such a Mess', url: 'https://www.wired.com/2009/08/ff-craigslist/', publisher: 'Wired', year: 2009, accessed: '2026-10-05' },
      {
        title: 'On Web Brutalism and Contemporary Web Design',
        url: 'https://quod.lib.umich.edu/d/dialectic/14932326.0001.107/--on-web-brutalism-and-contemporary-web-design?rgn=main&view=fulltext',
        publisher: 'Dialectic (AIGA / Michigan Publishing)',
        year: 2017,
        accessed: '2026-10-05',
      },
      { title: 'HTML Living Standard — 15 Rendering', url: 'https://html.spec.whatwg.org/multipage/rendering.html', publisher: 'WHATWG', accessed: '2026-10-05' },
      { title: 'craigslist.org, capture of 2 December 1998', url: 'https://web.archive.org/web/19981202212015/http://www.craigslist.org/', publisher: 'Internet Archive', year: 1998, accessed: '2026-10-05' },
      { title: 'Help On Mosaic v0.13', url: 'https://stuff.mit.edu/afs/sipb/project/www/doc/Mosaic-2.4/help-on-version-0.13.html', publisher: 'NCSA (mirror at MIT SIPB)', accessed: '2026-10-05' },
    ],
    archiveUrl: 'https://web.archive.org/web/19981202212015/http://www.craigslist.org/',
  },
  ficha: {
    documented: {
      es: 'Como un eco inalterable de la web primigenia, este paradigma resiste la obsolescencia mediante un brutalismo funcional. Su arquitectura cruda, despojada de ornamentos, prioriza la velocidad y la transmisión de información pura en una era de saturación visual [1][2][3].',
      en: 'Like an unalterable echo of the primordial web, this paradigm resists obsolescence through functional brutalism. Its raw architecture, stripped of ornaments, prioritizes speed and the transmission of pure information in an era of visual saturation [1][2][3].',
    },
    reading: {
      es: 'El estudio destila la estructura fundamental del navegador en una expresión contemporánea: contrastes absolutos, tipografía severa y líneas de demarcación implacables. Es una reducción a los átomos de la web [4][5][6].',
      en: 'The study distills the fundamental structure of the browser into a contemporary expression: absolute contrasts, severe typography, and relentless lines of demarcation. It is a reduction to the very atoms of the web [4][5][6].',
    },
    palette: {
      origin: 'documented',
      note: {
        es: 'Una dicotomía austera entre el blanco hueso y el negro azabache, puntuada únicamente por el azul cian de la hiperconectividad y el morado profundo de la memoria digital.',
        en: 'An austere dichotomy between bone white and jet black, punctuated only by the cyan blue of hyperconnectivity and the deep purple of digital memory.',
      },
    },
  },
  fonts: 'system-serif',
  colors: {
    bg: ['#fcfcfc', '#111111'],
    fg: ['#0f0f0f', '#f0f0f0'],
    fgMuted: ['#4f4f4f', '#a1a1a1'],
    surface: ['#fcfcfc', '#111111'],
    surfaceAlt: ['#f2f2f2', '#1c1c1c'],
    border: ['#262626', '#7a7a7a'],
    primary: ['#0c4bcc', '#689ff0'],
    primaryFg: ['#ffffff', '#061529'],
    accent: ['#4a187a', '#b37af0'],
    accentFg: ['#ffffff', '#180429'],
    info: ['#0c4bcc', '#689ff0'],
    infoFg: ['#ffffff', '#061529'],
    success: ['#126b1f', '#6fc47c'],
    successFg: ['#ffffff', '#051f08'],
    warning: ['#e6a800', '#e6ba22'],
    warningFg: ['#0f0f0f', '#1f1803'],
    danger: ['#b31212', '#eb6e6e'],
    dangerFg: ['#ffffff', '#2b0404'],
    focus: ['#0c4bcc', '#689ff0'],
  },
  type: { weightBody: 400, weightLabel: 400, weightDisplay: 700, displaySpacing: 'normal' },
  shape: { borderWidth: 1, radius: 0, radiusControl: 0, radiusButton: 0, radiusSmall: 0 },
  elevation: flat(),
  motion: { duration: 0, durationSlow: 0, ease: 'linear' },
  signature: './classifieds.css',
});
