import { defineTheme, flat } from '../../define';

export default defineTheme({
  id: 'classifieds',
  scene: 'usa',
  nativeScheme: 'light',
  name: { es: 'Clasificados', en: 'Classifieds' },
  tagline: { es: 'Texto, enlaces azules y nada más.', en: 'Text, blue links, nothing else.' },
  reference: {
    title: { es: 'craigslist (sitio web de anuncios clasificados)', en: 'craigslist (classified-ads website)' },
    authors: ['Craig Newmark'],
    date: 1995,
    place: { es: 'San Francisco, Estados Unidos', en: 'San Francisco, United States' },
    kind: 'web',
    sources: [
      { title: 'about > mission and history', url: 'https://www.craigslist.org/about/mission_and_history', publisher: 'craigslist', accessed: '2026-10-05' },
      { title: 'Why Craigslist Is Such a Mess', url: 'https://www.wired.com/2009/08/ff-craigslist/', publisher: 'Wired', year: 2009, accessed: '2026-10-05' },
      {
        title: 'On Web Brutalism and Contemporary Web Design',
        url: 'https://quod.lib.umich.edu/d/dialectic/14932326.0001.107/--on-web-brutalism-and-contemporary-web-design?rgn=main&view=fulltext',
        publisher: 'Dialectic (AIGA / Michigan Publishing)',
        year: 2017,
        accessed: '2026-10-05',
      },
      { title: 'HTML Living Standard — 15 Rendering', url: 'https://html.spec.whatwg.org/multipage/rendering.html', publisher: 'WHATWG', accessed: '2026-10-05' },
      { title: 'craigslist.org, capture of 2 December 1998', url: 'https://web.archive.org/web/19981202212015/http://www.craigslist.org/', publisher: 'Internet Archive', year: 1998, accessed: '2026-10-05' },
      { title: 'Help On Mosaic v0.13', url: 'https://stuff.mit.edu/afs/sipb/project/www/doc/Mosaic-2.4/help-on-version-0.13.html', publisher: 'NCSA (mirror at MIT SIPB)', accessed: '2026-10-05' },
    ],
    archiveUrl: 'https://web.archive.org/web/19981202212015/http://www.craigslist.org/',
  },
  ficha: {
    documented: {
      es: 'Craig Newmark empezó craigslist a principios de 1995 como una lista de correo de eventos en San Francisco; sus anuncios pasaron después a un sitio web [1]. En 2009 Wired observó que el sitio seguía pareciendo la web de los primeros años, hecho de largas listas de enlaces azules [2], y en 2017 la revista Dialectic de AIGA lo destacó como uno de los ejemplos más conocidos de brutalismo en la web [3]. La página archivada más antigua, de diciembre de 1998, no define colores de enlace propios, así que los enlaces salían con los colores por defecto del navegador [5].',
      en: 'Craig Newmark started craigslist in early 1995 as an e-mail list of San Francisco events; its posts later moved to a website [1]. In 2009 Wired observed that the site still looked like the early Web, built of long lists of blue links [2], and in 2017 the AIGA journal Dialectic singled it out as one of the best-known examples of brutalism on the web [3]. The earliest archived page, from December 1998, sets no link colours of its own, so links appeared in the browser’s defaults [5].',
    },
    reading: {
      es: 'El tema es esa página por defecto del navegador convertida en componentes: papel blanco, texto negro con serifa, un borde negro finísimo y ninguna sombra. Las acciones principales toman el azul de enlace no visitado #0000EE y el acento es el morado de visitado #551A8B [4][6]. Un botón fantasma se dibuja como un enlace subrayado que se vuelve rojo al pulsarlo, como un enlace activo; el rojo del tema es más oscuro que el #FF0000 del estándar para que el texto blanco de los botones de peligro siga siendo legible [4].',
      en: 'The theme is that default browser page made into components: white paper, black serif text, a hairline black edge and no shadows. Primary actions take the unvisited-link blue #0000EE and the accent is the visited purple #551A8B [4][6]. A ghost button is drawn as an underlined link that turns red while pressed, like an active link; the theme’s red is darker than the standard’s #FF0000 so that white text on danger buttons stays legible [4].',
    },
    palette: {
      origin: 'documented',
      note: {
        es: '#0000EE y #551A8B son los colores de enlace por defecto del estándar HTML actual; Mosaic ya dibujaba los enlaces no visitados en azul y los visitados en morado oscuro. El esquema oscuro es del tema.',
        en: '#0000EE and #551A8B are the default link colours of today’s HTML standard; Mosaic already drew unvisited links blue and visited ones dark purple. The dark scheme is the theme’s own.',
      },
    },
  },
  fonts: 'system-serif',
  colors: {
    bg: ['#ffffff', '#111111'],
    fg: ['#000000', '#eeeeee'],
    fgMuted: ['#555555', '#aaaaaa'],
    surface: ['#ffffff', '#111111'],
    surfaceAlt: ['#eeeeee', '#222222'],
    border: ['#000000', '#eeeeee'],
    primary: ['#0000ee', '#8ab4f8'],
    primaryFg: ['#ffffff', '#000000'],
    accent: ['#551a8b', '#c58af9'],
    accentFg: ['#ffffff', '#000000'],
    info: ['#0000ee', '#8ab4f8'],
    infoFg: ['#ffffff', '#000000'],
    success: ['#006600', '#6dd58c'],
    successFg: ['#ffffff', '#000000'],
    warning: '#ffcc00',
    warningFg: '#000000',
    danger: ['#cc0000', '#ff8080'],
    dangerFg: ['#ffffff', '#000000'],
    focus: ['#0000ee', '#8ab4f8'],
  },
  type: { weightBody: 400, weightLabel: 400, weightDisplay: 700, displaySpacing: 'normal' },
  shape: { borderWidth: 1, radius: 0, radiusControl: 0, radiusButton: 0, radiusSmall: 0 },
  elevation: flat(),
  motion: { duration: 0, durationSlow: 0, ease: 'linear' },
  signature: './classifieds.css',
});
