import { defineTheme, flat } from '../../define';

export default defineTheme({
  id: 'win95',
  scene: 'usa',
  nativeScheme: 'light',
  name: { es: 'Windows 95', en: 'Windows 95' },
  tagline: { es: 'La topografía de la productividad: relieves precisos esculpidos en grises utilitarios.', en: 'The topography of productivity: precise reliefs sculpted in utilitarian grays.' },
  reference: {
    title: { es: 'Windows 95 (interfaz gráfica de usuario)', en: 'Windows 95 (graphical user interface)' },
    authors: ['Microsoft'],
    date: 1995,
    place: { es: 'Redmond, Estados Unidos', en: 'Redmond, United States' },
    kind: 'software',
    sources: [
      {
        title: 'The Windows Interface Guidelines for Software Design',
        url: 'https://archive.org/details/windowsinterface00micr',
        publisher: 'Microsoft Press (Internet Archive)',
        year: 1995,
        accessed: '2026-10-08',
      },
      {
        title: 'GetSysColor function (winuser.h)',
        url: 'https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsyscolor',
        publisher: 'Microsoft Learn',
        accessed: '2026-10-08',
      },
    ],
  },
  ficha: {
    documented: {
      es: 'La interfaz que democratizó la informática. Sus directrices de diseño definieron un paradigma tridimensional mediante un magistral uso de sombras direccionales, otorgando a cada elemento una presencia táctil innegable [1][2].',
      en: 'The interface that democratized computing. Its design guidelines defined a three-dimensional paradigm through a masterful use of directional shadows, granting each element an undeniable tactile presence [1][2].',
    },
    reading: {
      es: 'El tema examina la ilusión de profundidad a través de sus cuatro tonos de contorno. Al interactuar, los componentes se hunden en el lienzo grisáceo. Una estética utilitaria que se eleva a la categoría de arte industrial.',
      en: 'The theme examines the illusion of depth through its four contour tones. Upon interaction, components sink into the grayish canvas. A utilitarian aesthetic elevated to the realm of industrial art.',
    },
    palette: {
      origin: 'interpreted',
      note: {
        es: 'Reinterpretamos el histórico gris #c0c0c0 y el azul marino clásico, refinando su saturación. Los tonos de acento y las sombras se han profundizado meticulosamente para asegurar una elegancia y legibilidad impecables.',
        en: 'We reinterpret the historic #c0c0c0 gray and classic navy blue, refining their saturation. Accent tones and shadows have been meticulously deepened to ensure impeccable elegance and legibility.',
      },
    },
  },
  fonts: 'system-sans',
  colors: {
    bg: ['#c0c0c0', '#141414'],
    fg: ['#111111', '#ffffff'],
    fgMuted: ['#444444', '#b3b3b3'],
    surface: ['#c0c0c0', '#1a1a1a'],
    surfaceAlt: ['#dfdfdf', '#222222'],
    border: ['#111111', '#dddddd'],
    primary: ['#000080', '#4a6eb0'],
    primaryFg: ['#ffffff', '#ffffff'],
    accent: ['#000080', '#4a6eb0'],
    accentFg: ['#ffffff', '#ffffff'],
    info: ['#000080', '#8ab4f8'],
    infoFg: ['#ffffff', '#111111'],
    success: ['#006600', '#6dd58c'],
    successFg: ['#ffffff', '#111111'],
    warning: ['#b38f00', '#e6c300'],
    warningFg: ['#111111', '#111111'],
    danger: ['#8b0000', '#ff8080'],
    dangerFg: ['#ffffff', '#111111'],
    focus: ['#111111', '#ffffff'],
  },
  type: { weightBody: 400, weightLabel: 700, weightDisplay: 700 },
  shape: { borderWidth: 1, radius: 2, radiusControl: 2, radiusButton: 2, radiusSmall: 1 },
  elevation: flat(),
  motion: { duration: 150, durationSlow: 300, ease: 'ease-out' },
  signature: './win95.css',
});
