import { defineTheme, flat } from '../../define';

export default defineTheme({
  id: 'xerox-star',
  scene: 'usa',
  nativeScheme: 'light',
  name: { es: 'Xerox Star', en: 'Xerox Star' },
  tagline: { es: 'Un bit por punto, escritorio gris, ventanas de papel.', en: 'One bit a dot, a grey desktop, paper windows.' },
  reference: {
    title: { es: 'Xerox Star (sistema de información 8010)', en: 'Xerox Star (8010 Information System)' },
    authors: ['David Canfield Smith', 'Charles Irby', 'Ralph Kimball', 'Bill Verplank', 'Eric Harslem'],
    date: 1981,
    place: { es: 'El Segundo y Palo Alto, Estados Unidos', en: 'El Segundo and Palo Alto, United States' },
    kind: 'software',
    sources: [
      { title: 'Byte, April 1982: Human Factors Engineering', url: 'https://archive.org/details/byte-magazine-1982-04', publisher: 'BYTE (Internet Archive)', year: 1982, accessed: '2026-10-09' },
      { title: 'Designing the Star User Interface', url: 'https://www.guidebookgallery.org/articles/designingthestaruserinterface', publisher: 'GUIdebook', year: 1982, accessed: '2026-10-09' },
      { title: 'The Xerox Star: A Retrospective', url: 'https://guidebookgallery.org/articles/thexeroxstararetrospective', publisher: 'GUIdebook', year: 1989, accessed: '2026-10-09' },
      { title: 'Xerox Star', url: 'https://en.wikipedia.org/wiki/Xerox_Star', publisher: 'Wikipedia', accessed: '2026-10-09' },
      { title: 'Xerox Star', url: 'https://digibarn.com/collections/software/xerox-star/index.html', publisher: 'DigiBarn Computer Museum', accessed: '2026-10-09' },
    ],
    image: {
      file: 'xerox-star.avif',
      width: 1600,
      height: 2133,
      alt: {
        es: 'Un Xerox Star 8010 en exhibición: el gabinete color crema en el piso y, sobre la mesa, el monitor, el teclado y el ratón de dos botones.',
        en: 'A Xerox Star 8010 on display: the cream cabinet on the floor and, on the table, the monitor, the keyboard and the two-button mouse.',
      },
      author: 'vonguard',
      license: 'CC-BY-SA-2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Xerox_Star_8010_(2).jpg',
    },
  },
  ficha: {
    documented: {
      es: 'El Star salió en 1981 [4], y su equipo de diseño explicó la interfaz en la revista BYTE en abril de 1982 [1][2]. La pantalla era un mapa de bits en blanco y negro de 1024 × 808 puntos, a 72 por pulgada, y cada punto se controlaba por separado [2][4]. Los documentos se veían blancos, como papel, sobre un escritorio gris, y los iconos se alineaban en una retícula de cuadros de una pulgada; un icono seleccionado se invertía a negro [2][3]. Las propiedades activas de una hoja de propiedades se marcaban en video inverso, y el cursor cambiaba de forma según el estado del sistema [5].',
      en: 'The Star shipped in 1981 [4], and its design team described the interface in BYTE in April 1982 [1][2]. The screen was a black-and-white bitmap of 1024 × 808 dots at 72 per inch, each dot controlled on its own [2][4]. Documents looked white, like paper, on a grey desktop, and icons sat on a grid of one-inch squares; a selected icon turned inverse, to black [2][3]. Properties in effect on a property sheet were shown in reverse video, and the cursor changed shape with the state of the system [5].',
    },
    reading: {
      es: 'El tema es de un solo bit: tinta negra sobre papel blanco, sin grises intermedios entre sus colores. El gris del escritorio se hace con una trama de puntos, la única forma de tener gris en una pantalla de un bit. Botones y tarjetas llevan borde de 2 px y sombra dura, y lo activo se invierte a negro, como un icono seleccionado. La serif del sistema es una lectura: las fuentes nombran Classic y Modern, pero ninguna identifica su dibujo.',
      en: 'The theme is one bit deep: black ink on white paper, with no in-between greys among its colours. The grey of the desktop is made with a dot pattern, the only way to get grey on a one-bit screen. Buttons and cards carry a 2 px border and a hard shadow, and what is active turns black, like a selected icon. The system serif is a reading: the sources name Classic and Modern, but none identifies how they were drawn.',
    },
    palette: {
      origin: 'interpreted',
      note: {
        es: 'La pantalla era de un bit, así que solo había blanco y negro; el tema usa un negro apenas suavizado.',
        en: 'The screen was one bit deep, so there was only black and white; the theme uses a barely softened black.',
      },
    },
    lettering: {
      original: { name: 'Classic, Modern', kind: 'bitmap' },
      documented: {
        es: 'El artículo del equipo del Star en BYTE pone como ejemplo un documento con el texto normal en Classic de 10 puntos y otro en Modern itálica de 12 [2]. La pantalla era de mapa de bits a 72 puntos por pulgada, y el mismo artículo advierte que enseñar la página tal como se imprime obliga a dibujar con mucho cuidado las fuentes de pantalla para que se lean [2].',
        en: 'The Star team’s article in BYTE gives as examples one document with its normal text in 10-point Classic and another in 12-point Modern italic [2]. The screen was a 72-dot-per-inch bitmap, and the same article warns that showing the page as it will print means drawing the screen fonts with great care if they are to stay readable [2].',
      },
      substitute: {
        es: 'El tema usa la serif del sistema. Como ninguna fuente que consultamos identifica el dibujo de Classic ni el de Modern, no imita ninguna; la serif lee el Star como un sistema pensado para la página impresa.',
        en: 'The theme uses the system serif. Since no source we consulted identifies how Classic or Modern were drawn, it imitates neither; the serif reads the Star as a system made for the printed page.',
      },
    },
  },
  fonts: 'system-serif',
  colors: {
    bg: ['#ffffff', '#111111'],
    fg: ['#111111', '#ffffff'],
    fgMuted: ['#111111', '#ffffff'],
    surface: ['#ffffff', '#111111'],
    surfaceAlt: ['#ffffff', '#111111'],
    border: ['#111111', '#ffffff'],
    primary: ['#111111', '#ffffff'],
    primaryFg: ['#ffffff', '#111111'],
    accent: ['#111111', '#ffffff'],
    accentFg: ['#ffffff', '#111111'],
    info: ['#111111', '#ffffff'],
    infoFg: ['#ffffff', '#111111'],
    success: ['#111111', '#ffffff'],
    successFg: ['#ffffff', '#111111'],
    warning: ['#111111', '#ffffff'],
    warningFg: ['#ffffff', '#111111'],
    danger: ['#111111', '#ffffff'],
    dangerFg: ['#ffffff', '#111111'],
    focus: ['#111111', '#ffffff'],
  },
  type: { weightBody: 400, weightLabel: 700, weightDisplay: 700 },
  shape: { borderWidth: 2, radius: 2, radiusControl: 2, radiusButton: 2, radiusSmall: 1 },
  elevation: flat(),
  motion: { duration: 0, durationSlow: 0, ease: 'linear' },
  signature: './xerox-star.css',
});
