import { defineTheme, hardShadow } from '../../define';
import { concrete } from '../../families';

export default defineTheme({
  id: 'sesc-pompeia',
  scene: 'latam',
  nativeScheme: 'light',
  name: { es: 'SESC Pompéia', en: 'SESC Pompéia' },
  tagline: { es: 'Cuerpos de hormigón desgarrados por la vida: intersticios rojos y el espíritu de la congregación cívica.', en: 'Bodies of concrete torn by life: red interstices and the spirit of civic congregation.' },
  reference: {
    title: { es: 'SESC Pompéia', en: 'SESC Pompéia' },
    original: { text: 'Centro de Lazer Fábrica da Pompéia', lang: 'pt' },
    authors: ['Lina Bo Bardi', 'André Vainer', 'Marcelo Carvalho Ferraz'],
    date: [1977, 1986],
    place: { es: 'Pompeia, São Paulo, Brasil', en: 'Pompeia, São Paulo, Brazil' },
    kind: 'architecture',
    sources: [
      { title: 'Numa velha fábrica de tambores. Sesc Pompeia comemora 25 anos', url: 'https://vitruvius.com.br/revistas/read/minhacidade/08.093/1897', publisher: 'Vitruvius (Minha Cidade 093.01)', year: 2008, accessed: '2026-10-05' },
      { title: 'Clássicos da Arquitetura: SESC Pompéia / Lina Bo Bardi', url: 'https://www.archdaily.com/pt/01-153205/classicos-da-arquitetura-sesc-pompeia-slash-lina-bo-bardi', publisher: 'ArchDaily Brasil', year: 2013, accessed: '2026-10-05' },
      {
        title: 'Lina’s Red: Explore the Use of the Color as Prominent Element in Lina Bo Bardi’s Works',
        url: 'https://www.archdaily.com/1005415/linas-red-explore-the-use-of-the-color-as-prominent-element-in-lina-bo-bardis-works',
        publisher: 'ArchDaily',
        year: 2023,
        accessed: '2026-10-05',
      },
      { title: 'As janelas do Conjunto Esportivo do Sesc Pompeia', url: 'https://portal.sescsp.org.br/online/artigo/13584_AS+JANELAS+DO+CONJUNTO+ESPORTIVO+DO+SESC+POMPEIA', publisher: 'Sesc São Paulo', year: 2019, accessed: '2026-10-05' },
      { title: 'Omnibus-Type', url: 'https://thepunch.studio/foundry/omnibus-type', publisher: 'The Punch', accessed: '2026-10-05' },
    ],
    image: {
      file: 'sesc-pompeia.avif',
      width: 1600,
      height: 2133,
      alt: {
        es: 'Las aberturas irregulares de la torre deportiva de hormigón, con celosías rojas, sobre la antigua fábrica de ladrillo.',
        en: 'The concrete sports tower’s irregular openings, fitted with red lattices, above the old brick factory.',
      },
      author: 'Joalpe',
      license: 'CC-BY-SA-4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:SESC_Pompeia_-_S%C3%A3o_Paulo_-_20220726142122.jpg',
    },
  },
  ficha: {
    documented: {
      es: 'La intervención magistral de Lina Bo Bardi (1977-1986) en esta antigua fábrica de tambores redefinió el Brutalismo sudamericano al inyectarle una profunda empatía social [1]. Los colosales bloques deportivos de hormigón visto fueron perforados con aberturas irregulares, similares a cavernas prehistóricas, que permitían la libre circulación de los elementos [2][4]. Acentuado por pasarelas aéreas y barandillas de un rojo vital [3], el complejo es una catedral de lo cotidiano, donde la brutalidad material abraza la calidez humana.',
      en: 'Lina Bo Bardi’s masterful intervention (1977–1986) in this former drum factory redefined South American Brutalism by injecting it with profound social empathy [1]. The colossal exposed concrete sports blocks were pierced with irregular, cave-like apertures that allowed the free circulation of the elements [2][4]. Accentuated by aerial walkways and handrails painted a vital red [3], the complex stands as a cathedral of the everyday, where material brutality embraces human warmth.',
    },
    reading: {
      es: 'Un diseño que emula las fracturas orgánicas del hormigón. El sistema introduce bordes asimétricos y esquinas deliberadamente imperfectas, invocando la cualidad artesanal y táctil de la obra de Bo Bardi. El rojo visceral actúa como el hilo conductor, cortando visualmente a través del estoico lienzo gris perla para indicar jerarquía y flujo interaccional [5].',
      en: 'A design that emulates the organic fractures of concrete. The system introduces asymmetrical borders and deliberately imperfect corners, invoking the artisanal, haptic quality of Bo Bardi’s work. The visceral red acts as the guiding thread, slicing visually through the stoic pearl-grey canvas to indicate hierarchy and interactional flow [5].',
    },
    palette: {
      origin: 'interpreted',
      note: {
        es: 'El contraste poético: el gris terroso de los encofrados besado por el icónico escarlata brasileño.',
        en: 'The poetic contrast: the earthy grey of timber formworks kissed by the iconic Brazilian scarlet.',
      },
    },
  },
  fonts: { sans: 'chivo', mono: 'chivo-mono' },
  colors: {
    bg: ['#d1cec7', '#1a1918'],
    fg: ['#1c1a18', '#e8e5df'],
    fgMuted: ['#474440', '#a39f98'],
    surface: ['#eae7e1', '#242321'],
    surfaceAlt: ['#dedcd5', '#33302e'],
    border: ['#211e1c', '#cfcbc5'],
    primary: ['#a61914', '#f25b55'],
    primaryFg: ['#ffffff', '#240402'],
    accent: ['#2b5a78', '#6fa2c4'],
    accentFg: ['#ffffff', '#061621'],
    info: ['#2b5a78', '#6fa2c4'],
    infoFg: ['#ffffff', '#061621'],
    success: ['#2e7037', '#6abf76'],
    successFg: ['#ffffff', '#031a08'],
    warning: ['#b8841a', '#e6b54c'],
    warningFg: ['#1c1a18', '#211502'],
    danger: ['#a61914', '#ff7b75'],
    dangerFg: ['#ffffff', '#240402'],
    focus: ['#a61914', '#f25b55'],
  },
  type: { weightBody: 400, weightLabel: 700, weightDisplay: 900, labelSpacing: '0em', displaySpacing: '-0.03em' },
  shape: { borderWidth: 2, radius: 0, radiusControl: 0, radiusButton: 4, radiusSmall: 0 },
  elevation: hardShadow(5),
  families: [concrete({ grain: 0.05, formwork: 0.04, board: 16 })],
  signature: './sesc-pompeia.css',
});
