/** The theme catalog as the site uses it (generated by scripts/build-study.mjs). */
import { CATALOG } from '../../study/.generated/catalog';
import type { CatalogEntry } from '../../study/catalog';

export { CATALOG };

export const ENTRIES: ReadonlyMap<string, CatalogEntry> = new Map(CATALOG.map((entry) => [entry.id, entry]));

/** Themes made for the study, in catalog order (scene folder, then id). */
export const STUDY_ENTRIES: readonly CatalogEntry[] = CATALOG.filter((entry) => !entry.predatesStudy);
